version: "3.8"

services:
  # serwis 1: nasza aplikacja
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - APP_VERSION=v3.0-db
      - DB_HOST=db
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
    depends_on:
      - db

  # serwis 2: baza danych PostgreSQL
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
